### ISSUE TITLE
Problem: there are duplicated hard coded informations in integration tests

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#10]
follow up on: https://github.com/crypto-org-chain/cronos/pull/8

The genesis keys and addresses are duplicated and hard coded in different places, better to keep them in single place for easier maintenance in the future.

**Comment by damoncro** [comment]
I'll look into this one.

**Comment by damoncro** [comment]
I think this issue could be done by simple way or complicated way. There are some possible outcomes that I can think of:

1. For easy maintenance. keys and address are duplicated in my files, in scripts, python files, yaml files, toml etc. The most important thing I guess is consolidating all the keys and addresses into one file (maybe just simply called `keys.yaml` or` keys.toml` or `.env`.
2. For safety. Provide a way to control the keys generations. Maybe a test to scan all files, if they appear in non-whitelist files, should fail the test. 
3. Complicated: For even more safety. May use keystore, gpg, or use import another test framework - brownie, which I guess can provide a good key management solution, key management and more robust smart contract tests. I tested on cronos, it works great.

and more.

@yihuang @tomtau Free free to input your ideas, so that I can pick up the right way to do.

**Comment by yihuang** [comment]
Since it's only for testing, I think the simpler the better.
For the key management tool, there are also `ethsign` which is included in the dapp package, I guess similar to `brownie`? but they don't work with cosmos cli I guess?

**Comment by damoncro** [comment]
I think so, would work on the simple way.
