### ISSUE TITLE
Problem: Gravity bridge orchestrator always run with relayer

### ISSUE THREAD

**Issue by calvinaco** [crypto-org-chain/cronos#100]
Provide a flag to enable/disable running the relayer, or just don't run relayer with it.

That way validators can decide to run only the orchestrator to validate the traffic but not to relay the packet.

**Comment by yihuang** [comment]
Do you mean only do etherem -> cronos, but don't do cronos -> ethereum?

**Comment by thomas-nguy** [comment]
Yes

the orchestrator main loop also run the relayer main loop

https://github.com/PeggyJV/gravity-bridge/blob/main/orchestrator/orchestrator/src/main_loop.rs#L82

we want for the partners to be able to disable the relayer part which requires some ETH fee

**Comment by yihuang** [comment]
If the orchestrator doesn't have enough eth balance on ethereum, it naturally can't relay successfully.
Or after https://github.com/crypto-org-chain/cronos/issues/99 is implemented, he can set an extremely high profit rate to defactorly disable relaying.

**Comment by thomas-nguy** [comment]
I think for the first phase, partners does not want to develop anything for the relayer and we should help them to setup the orchestrator correctly. So being able to run orchestrator without relayer needs to be simplify

If partner choose to run relayer, there are also discussion if we should allow or not "competition" between relayers.
Because we will endup losing gas for nothing since only one can submit batch correctly (the highest gas price setup win)

**Comment by yihuang** [comment]
https://github.com/PeggyJV/gravity-bridge/pull/210

it seems already implemented in upstream.
