### ISSUE TITLE
Problem: not possible to cancel SendToEthereum transactions

### ISSUE THREAD

**Issue by thomas-nguy** [crypto-org-chain/cronos#389]
Implement a new events in the EVM hooks to be able to cancel an "unbatched" transaction.

Critical points are:
- Verify the sender address and allows to unbatch only transactions related to him.
- Contract needs also to refund the user if it is successfull

**Comment by yihuang** [comment]
Maybe with the [eip-712 feature in ethermint](https://github.com/tharsis/ethermint/pull/950) now, we don't need to add these events anymore, ask the client to sign a cosmos message directly using metamask.

**Comment by thomas-nguy** [comment]
hmmm with our current design, cosmos native tokens are still managed by the smart contract. We cannot use EIP-712 without major architecture change.

**Comment by yihuang** [comment]
> hmmm with our current design, cosmos native tokens are still managed by the smart contract. We cannot use EIP-712 without major architecture change.

I see, currently, the internal `MsgSendToEthereum`'s sender is the contract, if we transfer the native token to user first, we can set the sender to the user. But then when the user cancels the msg, he'll be left with the native tokens, need another action to move it back to erc20 again. maybe indeed make sense to add a cancel event for it since we are already here.
Is it possible to do a major architecture change right now though, are the related frontend support almost done now?

**Comment by thomas-nguy** [comment]
I think it is still possible the change the architecture but we might consider that we have a lot of tokens already bridged 
(CRO + solo machine bridged tokens + cosmos tokens)

But we can spend some time to think about a better architecture
