### ISSUE TITLE
Problem: can't get back tx result of false-failed tx

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#437]
There's a known issue in mainnet that a committed tx disappears in RPC and explorer, although the issue itself is fixed in new version, there are still old tx results need to fix somehow.
One solution is provide an API to get back the tx execution result by replaying.

**Comment by tsutsu** [comment]
Can I propose an alternate solution, that won't require adding business logic to RPC nodes?

How about, *when running as a non-validator*, cronos configures ethermint to ignore the per-block-embedded gas limits altogether?

* Validators would still adhere to gas limits when auditing one-another's blocks as parent blocks, so the network's integrity wouldn't be impacted.
* RPC nodes would (after a complete resync) end up with a corrected history, containing all txs+receipts+logs.
* The QuickSync snapshots could be made from a re-synced RPC node, enabling most RPC services to skip doing a full re-sync of their own.

If, despite Cronos Mainnet being a PoA network, there are still concerns about the network integrity in the face of many nodes potentially operating without gas limits, the logic for operating without a block gas limit could be bounded to only apply up to the block-height where the problem was resolved. (In other words, add a fork-block on the ethermint layer, where the block-gas-limit override applies only up to the fork block.)

**Comment by yihuang** [comment]
The problem is that'll break the hashes (app_hash, last_results_hash) in block header.

**Comment by tsutsu** [comment]
Ah; so Ethermint persists non-Ethereum-consensus "cache" databases like "transactions available to RPC" into the regular Cosmos-SDK application multistore (seemingly, `EvmKeeper`)? That seems like asking for trouble in a number of ways; though I do understand their motivation re: ability to fast/snapshot-sync this derived state along with the consensus state.

Then how about this?

- Add a one-time data-migration message type (i.e. a message that persists a global flag into the state that prevents it from ever being run again), that anyone can run
- When this message is executed by a node, it will run through the blocks that were corrupted (either scaning all blocks for these spuriously-failed txs, or just using an explicit embedded list of heights) and will use the code you've written to replay those blocks, but _for effect_ (i.e. with `ctx.checkTx == false`) rather than for simulation — causing the EvmKeeper state to actually be updated.
- As this message is executed as part of consensus, all nodes will end up on the new app_hash, whether by executing the data-migration message (validators) or by syncing in the updates to the EvmKeeper store (non-validators.)

**Comment by yihuang** [comment]
Thanks for suggestion, but the issue is not the EvmKeeper state, but the tx results, particularly the result code and events, they are stored in tendermint db. I'm not sure if it's feasible to iterate the tendermint db to modify the tx result and event indexing.
Right now, the solution is to create a new RPC api to replay a specific block: https://github.com/crypto-org-chain/cronos/pull/438, so we can recover the execution results of those txs.

**Comment by tsutsu** [comment]
> I'm not sure if it's feasible to iterate the tendermint db to modify the tx result and event indexing.

I'm not clear on why you'd have to.

The Ethermint app layer shouldn't need to care that the original Tendermint block's payload was marked as failed, and that the resulting Tendermint-layer events were dropped, because from Ethermint's perspective, those are both implementation details of the consensus layer. Yes, Ethermint's implementation of `GetTxByEthHash` needs to find the transactions _somewhere_ in the Tendermint tx index — but that "somewhere" doesn't need to be the original *Tendermint* block that created those transactions.

Or, to put that another way: Tendermint blocks don't have to have a one-to-one relationship with Ethereum blocks; that's just the de-facto relationship you get by using Ethermint as a black-box abstraction. Tendermint blocks are just consensus-timesteps where payloads of Cosmos-SDK CQRS commands (messages) are delivered; those messages, provided you write your own handlers for them, can do anything to any state you like, and can emit any events you like for Tendermint to index. Those events can be the same ones Ethermint uses.

Or, to be direct: you can, in a migration script or custom handler, add more transactions to existing Ethereum blocks, by emitting the `TypeMsgEthereumTx` messages that Ethermint would emit itself as results of the Tendermint block that executes the handler, but where those tx messages are tagged as being of the Ethereum-semantic block-height they belong to. Ethermint's RPC methods will then, naturally, pick them up.
