### ISSUE TITLE
Stuck on starting

### ISSUE THREAD

**Issue by unlimittt** [crypto-org-chain/cronos#687]
**Describe the bug**
Always stuck after unpacking data from quicksync, while normal start is ok. cronosd 8.0.1

2:34PM INF Unlocking keyring
2:34PM INF starting ABCI with Tendermint

**To Reproduce**
cronosd init [moniker] --chain-id cronosmainnet_25-1
replace genesis.json from cronos-mainnet/master/cronosmainnet_25-1/genesis.json
add seeds to config.toml
unpack data folder from quicksync.io

**Expected behavior**
Starts normally

**Desktop (please complete the following information):**
 - Device: Ubuntu 22.04 Desktop

**Comment by JayT106** [comment]
Are you using cronosd `0.8.1`?
This release updated some upstream libs. we are using a new iavl dependency (v0.17 -> v0.19) which causes this issue. Because the iavl will re-index the whole data if it finds data have not been re-indexed at the first execution. It might stuck for several hours even a day. After the new iavl indexed the data, the node should start normally and more faster!

**Comment by unlimittt** [comment]
Strange behavior downloaded 
[cronos_0.8.1_Linux_x86_64.tar.gz](https://github.com/crypto-org-chain/cronos/releases/download/v0.8.1/cronos_0.8.1_Linux_x86_64.tar.gz)

but cronosd version shows 0.8.0

**Comment by unlimittt** [comment]
Not stuck but just needs more time to start.

**Comment by cifer76** [comment]
@JayT106 thanks for the explanation, may I have another question, will this re-indexing work benefits the history query scenarios? i.e. querying ancient blocks & state.

**Comment by lcgogo** [comment]
> 

How can I know it is in reindex or hanged? The log prints nothing even I set the loglevel as debug when I update 0.8.0 to 0.8.1

**Comment by yihuang** [comment]
0.8.2 will print a log, and add a new config option to disable the new iavl index, will be available soon.
